# See https://github.com/linux-surface/linux-surface/wiki/Disk-Encryption

add_drivers+=" surface_aggregator surface_aggregator_registry surface_aggregator_hub surface_hid_core surface_hid 8250_dw intel_lpss intel_lpss_pci pinctrl_tigerlake "
